#!/bin/bash

# THIS IS JUST AN EXAMPLE

#docker run $DOCKEROPTS --rm --net mycluster1net_10.1.0 --privileged -h hpcc-baseimage --name hpcc-baseimage -v /home/jsmith/git/docker/hpcc/shared/:/shared -v /home/jsmith/git/docker/hpcc/clusterFolders/mycluster1/:/data -it jcs/hpcc-baseimage:latest $@
docker run $DOCKEROPTS --rm --privileged -h hpcc-baseimage --name hpcc-baseimage -v /home/jsmith/git/docker/hpcc/shared/:/shared -v /home/jsmith/git/docker/hpcc/clusterFolders/mycluster1/:/data -it jcs/hpcc-baseimage:latest $@
