#!/bin/bash

if [ $# -lt 2 ]; then
 echo Usage: run NAME IP
 exit 1
fi

name=$1
ip=$2

mythornet=$(docker network ls | awk '{print $2}' | grep '^mythornet')
if [ -z "$mythornet" ]; then
  docker network create --subnet=192.168.10.0/24 mythornet
fi

echo docker run -d --rm --net mythornet --ip ${ip} --name ${name} -v /home/jsmith/dev/docker/sharedfolder:/data -ti jcs/thormasterdev:0.1 ${name}
docker run -d --rm --net mythornet --ip ${ip} --name ${name} -v /home/jsmith/dev/git/HPCC-Platform:/home/build/HPCC-Platform -v /home/jsmith/dev/docker/sharedfolder:/data -ti jcs/thormasterdev:0.1 ${name}

