#!/bin/bash

# Run by provisioner
: <<'COMMENTBLOCK'

1) StorageArrays should already exist (or rather already be provisioned separately)
2) In ENGINE on demand scenario.. what criteria does job want:
   a) Fast LOCAL storage?
   b) Number of processing nodes


COMMENTBLOCk

if [ $# -lt 2 ]; then
  echo Usage: runcluster CLUSTERNAME NUMCONTAINERS
  exit 1
fi

cluster=$1
numContainers=$2

echo "RUNNING: ./runhpcc "${cluster}_thormaster" 192.168.10.2"
./runhpcc "${cluster}_thormaster" 192.168.10.2
for container in $(seq 1 ${numContainers}); do
  let "ipnum = 2 + ${container}"
  echo "RUNNING: ./runhpcc "${cluster}_thorslave${container}" 192.168.10.${ipnum}"
  ./runhpcc "${cluster}_thorslave${container}" 192.168.10.${ipnum}
done
