apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-thormaster-svc
  labels:
    app: {{ .Release.Name }}-thormaster-svc
spec:
  ports:
    - port: {{ .Values.master.port }}
  selector:
    app: {{ .Release.Name }}-thormaster-svc
