apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydali
spec:
  selector:
    matchLabels:
      app: mydali
  template:
    metadata:
      labels:
        app: mydali
    spec:
      containers:
        - name: mydali
          image: jcs/hpcc-dali:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
