apiVersion: apps/v1
kind: Deployment
metadata:
  name: myesp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: myesp
  template:
    metadata:
      labels:
        app: myesp
    spec:
      containers:
        - name: myesp
          image: jcs/hpcc-esp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8010
