apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dali
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dali
    spec:
      containers:
        - name: {{ .Release.Name }}-dali
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
