#!/bin/bash

if [ $# -lt 2 ]; then
  echo Usage: runluster CLUSTERNAME NUMSLAVES
  exit 1
fi

cluster=$1
numslaves=$2

masterimagename=${cluster}_thormaster
echo "RUNNING: ./runhpcc "${cluster}_thormaster" 192.168.10.2 ${masterimagename}"
./runhpcc "${cluster}_thormaster" 192.168.10.2 ${masterimagename}
for slave in $(seq 1 ${numslaves}); do
  let "ipnum = 2 + ${slave}"
  imagename=${cluster}_thorslave${slave}
  echo "RUNNING: ./runhpcc "${cluster}_thorslave${slave}" 192.168.10.${ipnum} ${imagename}"
  ./runhpcc "${cluster}_thorslave${slave}" 192.168.10.${ipnum} ${slavenum} ${imagename}
done
