# Default values for thor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

slaves: 2

global:
  imagePullPolicy: Never
  dali: thedali
  clusterNames: thecluster

master:
  image: jcs/hpcc-thormaster:latest
  port: 20000

slave:
  image: jcs/hpcc-thorslave:latest
  port: 20100

