#!/bin/bash

if [ $# -lt 1 ]; then
 echo Usage: build SRCDIR
 exit 1
fi

echo rsync -avzh $ –cvs-exclude '.git' $1 .
rsync -avz --exclude .git/ --exclude .gitignore --exclude .gitmodules $1/ HPCC-Platform/

docker build -t jcs/hpccbuilddevpkg:latest .
