#!/bin/bash

kubectl delete deployment.apps/mythormaster
kubectl delete deployment.apps/mythorslave
#for slaveid in $(docker ps -q --filter ancestor=jcs/hpcc-thorslave)
#do
#	echo Stopping slave id: $slaveid
#	docker stop $slaveid
#done

kubectl delete deployment.apps/myeclagent
kubectl delete deployment.apps/myeclccserver
kubectl delete deployment.apps/myesp
kubectl delete deployment.apps/mydali
kubectl delete service/mythormaster
kubectl delete service/myesp
kubectl delete service/mydali
