#!/bin/bash

if [ $# -lt 2 ]; then
 echo Usage: build Repo Branch
 exit 1
fi
repo=$1
branch=$2

docker build --build-arg repo=${repo} --build-arg branch=${branch} -t jcs/hpccbuild:latest -t jcs/hpccbuild:${branch} .

