FROM jcs/hpcc-baseimage

EXPOSE 8010

ENV DALIHOST="hpcc-dali"
ENV ESPHOST="hpcc-esp"
RUN cat $HPCC_INSTALL_BASE/etc/HPCCSystems/environment.xml | xmlstarlet ed -u "/Environment/Software/DaliServerProcess/Instance/@netAddress" -v $DALIHOST | xmlstarlet ed -u "/Environment/Hardware/Computer/@netAddress" -v $DALIHOST | xmlstarlet ed -u "/Environment/Software/EspProcess/Instance/@netAddress" -v $ESPHOST | xmlstarlet ed -u '//*[@netAddress="PLACEHOLDER"]/@netAddress' -v "." > tmp.xml
RUN mv tmp.xml $HPCC_INSTALL_BASE/etc/HPCCSystems/environment.xml
RUN cat $HPCC_INSTALL_BASE/etc/HPCCSystems/environment.xml \
    | xmlstarlet ed -u "/Environment/Software/DaliServerProcess/Instance/@netAddress" -v $DALIHOST \
    | xmlstarlet ed -u "/Environment/Hardware/Computer/@netAddress" -v $DALIHOST \
    | xmlstarlet ed -u "/Environment/Software/EspProcess/Instance/@netAddress" -v $ESPHOST\
    | xmlstarlet ed -s "/Environment/Hardware" -t elem -n "Computer" \
    | xmlstarlet ed -s "/Environment/Hardware/Computer[2]" -t attr -n "computerType" -v "linuxmachine" \
    | xmlstarlet ed -s "/Environment/Hardware/Computer[2]" -t attr -n "domain" -v "localdomain" \
    | xmlstarlet ed -s "/Environment/Hardware/Computer[2]" -t attr -n "netAddress" -v "." \
    | xmlstarlet ed -u '/Environment/Software/DropZone/ServerList[@server="PLACEHOLDER"]/@server' -v "." \
    | xmlstarlet ed -u '//*[@netAddress="PLACEHOLDER"]/@netAddress' -v "." \
    > tmp.xml
RUN mv tmp.xml $HPCC_INSTALL_BASE/etc/HPCCSystems/environment.xml

# "myesp" because dealing with generic environment
CMD ["/scripts/init/start-hpcccomp.sh", "esp", "myesp"]
