apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-thor-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/run/desktop/mnt/host/wsl/hostmount"
